[build-system]
requires = ["maturin>=1.8,<2.0"]
build-backend = "maturin"

[project]
name = "numcodecs_wasm"
version = "0.1.0" # wasi 0.2.3
description = "numcodecs compression for codecs compiled to WebAssembly"

authors = [{ name = "Juniper Tyree", email = "juniper.tyree@helsinki.fi" }]
maintainers = [{ name = "Juniper Tyree", email = "juniper.tyree@helsinki.fi" }]

readme = "README.md"
license = { file = "LICENSE" }

requires-python = ">=3.10"

dependencies = [
    "numcodecs>=0.13.0,<0.16",
    "numcodecs-observers~=0.1.1",
    "numpy~=2.0",
    "typing-extensions~=4.6",
]

classifiers = [
    "Programming Language :: Rust",
    "Programming Language :: Python :: Implementation :: CPython",
    "Programming Language :: Python :: Implementation :: PyPy",
]

[dependency-groups]
dev = ["ruff~=0.9.0"]

[tool.maturin]
python-source = "py"
module-name = "numcodecs_wasm._wasm"
features = ["pyo3/extension-module"]
