(function() {var implementors = {
"numcodecs_bit_round":[["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/convert/trait.From.html\" title=\"trait core::convert::From\">From</a>&lt;<a class=\"enum\" href=\"https://juntyr.github.io/numcodecs-rs/numcodecs/array/enum.AnyArrayAssignError.html\" title=\"enum numcodecs::array::AnyArrayAssignError\">AnyArrayAssignError</a>&gt; for <a class=\"enum\" href=\"numcodecs_bit_round/enum.BitRoundCodecError.html\" title=\"enum numcodecs_bit_round::BitRoundCodecError\">BitRoundCodecError</a>"]],
"numcodecs_identity":[["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/convert/trait.From.html\" title=\"trait core::convert::From\">From</a>&lt;<a class=\"enum\" href=\"https://juntyr.github.io/numcodecs-rs/numcodecs/array/enum.AnyArrayAssignError.html\" title=\"enum numcodecs::array::AnyArrayAssignError\">AnyArrayAssignError</a>&gt; for <a class=\"enum\" href=\"numcodecs_identity/enum.IdentityCodecError.html\" title=\"enum numcodecs_identity::IdentityCodecError\">IdentityCodecError</a>"]],
"numcodecs_linear_quantize":[["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/convert/trait.From.html\" title=\"trait core::convert::From\">From</a>&lt;<a class=\"struct\" href=\"https://docs.rs/ndarray/0.15/ndarray/error/struct.ShapeError.html\" title=\"struct ndarray::error::ShapeError\">ShapeError</a>&gt; for <a class=\"enum\" href=\"numcodecs_linear_quantize/enum.LinearQuantizeCodecError.html\" title=\"enum numcodecs_linear_quantize::LinearQuantizeCodecError\">LinearQuantizeCodecError</a>"]],
"numcodecs_log":[["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/convert/trait.From.html\" title=\"trait core::convert::From\">From</a>&lt;<a class=\"enum\" href=\"https://juntyr.github.io/numcodecs-rs/numcodecs/array/enum.AnyArrayAssignError.html\" title=\"enum numcodecs::array::AnyArrayAssignError\">AnyArrayAssignError</a>&gt; for <a class=\"enum\" href=\"numcodecs_log/enum.LogCodecError.html\" title=\"enum numcodecs_log::LogCodecError\">LogCodecError</a>"]],
"numcodecs_reinterpret":[["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/convert/trait.From.html\" title=\"trait core::convert::From\">From</a>&lt;<a class=\"enum\" href=\"https://juntyr.github.io/numcodecs-rs/numcodecs/array/enum.AnyArrayAssignError.html\" title=\"enum numcodecs::array::AnyArrayAssignError\">AnyArrayAssignError</a>&gt; for <a class=\"enum\" href=\"numcodecs_reinterpret/enum.ReinterpretCodecError.html\" title=\"enum numcodecs_reinterpret::ReinterpretCodecError\">ReinterpretCodecError</a>"]],
"numcodecs_round":[["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/convert/trait.From.html\" title=\"trait core::convert::From\">From</a>&lt;<a class=\"enum\" href=\"https://juntyr.github.io/numcodecs-rs/numcodecs/array/enum.AnyArrayAssignError.html\" title=\"enum numcodecs::array::AnyArrayAssignError\">AnyArrayAssignError</a>&gt; for <a class=\"enum\" href=\"numcodecs_round/enum.RoundCodecError.html\" title=\"enum numcodecs_round::RoundCodecError\">RoundCodecError</a>"]],
"numcodecs_sz3":[["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/convert/trait.From.html\" title=\"trait core::convert::From\">From</a>&lt;<a class=\"enum\" href=\"numcodecs/array/enum.AnyArrayAssignError.html\" title=\"enum numcodecs::array::AnyArrayAssignError\">AnyArrayAssignError</a>&gt; for <a class=\"enum\" href=\"numcodecs_sz3/enum.Sz3CodecError.html\" title=\"enum numcodecs_sz3::Sz3CodecError\">Sz3CodecError</a>"],["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/convert/trait.From.html\" title=\"trait core::convert::From\">From</a>&lt;<a class=\"struct\" href=\"https://docs.rs/ndarray/0.15/ndarray/error/struct.ShapeError.html\" title=\"struct ndarray::error::ShapeError\">ShapeError</a>&gt; for <a class=\"enum\" href=\"numcodecs_sz3/enum.Sz3CodecError.html\" title=\"enum numcodecs_sz3::Sz3CodecError\">Sz3CodecError</a>"]],
"numcodecs_uniform_noise":[["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/convert/trait.From.html\" title=\"trait core::convert::From\">From</a>&lt;<a class=\"enum\" href=\"https://juntyr.github.io/numcodecs-rs/numcodecs/array/enum.AnyArrayAssignError.html\" title=\"enum numcodecs::array::AnyArrayAssignError\">AnyArrayAssignError</a>&gt; for <a class=\"enum\" href=\"numcodecs_uniform_noise/enum.UniformNoiseCodecError.html\" title=\"enum numcodecs_uniform_noise::UniformNoiseCodecError\">UniformNoiseCodecError</a>"]],
"numcodecs_zfp":[["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/convert/trait.From.html\" title=\"trait core::convert::From\">From</a>&lt;<a class=\"enum\" href=\"numcodecs/array/enum.AnyArrayAssignError.html\" title=\"enum numcodecs::array::AnyArrayAssignError\">AnyArrayAssignError</a>&gt; for <a class=\"enum\" href=\"numcodecs_zfp/enum.ZfpCodecError.html\" title=\"enum numcodecs_zfp::ZfpCodecError\">ZfpCodecError</a>"]],
"numcodecs_zlib":[["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/convert/trait.From.html\" title=\"trait core::convert::From\">From</a>&lt;<a class=\"enum\" href=\"https://juntyr.github.io/numcodecs-rs/numcodecs/array/enum.AnyArrayAssignError.html\" title=\"enum numcodecs::array::AnyArrayAssignError\">AnyArrayAssignError</a>&gt; for <a class=\"enum\" href=\"numcodecs_zlib/enum.ZlibCodecError.html\" title=\"enum numcodecs_zlib::ZlibCodecError\">ZlibCodecError</a>"]],
"numcodecs_zstd":[["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/convert/trait.From.html\" title=\"trait core::convert::From\">From</a>&lt;<a class=\"enum\" href=\"numcodecs/array/enum.AnyArrayAssignError.html\" title=\"enum numcodecs::array::AnyArrayAssignError\">AnyArrayAssignError</a>&gt; for <a class=\"enum\" href=\"numcodecs_zstd/enum.ZstdCodecError.html\" title=\"enum numcodecs_zstd::ZstdCodecError\">ZstdCodecError</a>"]]
};if (window.register_implementors) {window.register_implementors(implementors);} else {window.pending_implementors = implementors;}})()