[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "numcodecs_wasm_%package_suffix%"
version = "%crate-version%"
description = "numcodecs-%crate-suffix% compression codec compiled to WebAssembly"

authors = [{ name = "Juniper Tyree", email = "juniper.tyree@helsinki.fi" }]
maintainers = [{ name = "Juniper Tyree", email = "juniper.tyree@helsinki.fi" }]

readme = "README.md"
license = { file = "LICENSE" }

requires-python = ">=3.10"

dependencies = [
    "numcodecs-wasm~=0.1.5", # wasi 0.2.3
]

[project.entry-points."numcodecs.codecs"]
"%codec-id%" = "numcodecs_wasm_%package_suffix%:%CodecName%"

[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools.package-data]
numcodecs_wasm_%package_suffix% = ["codec.wasm"]

[tool.setuptools]
# Workaround for
# https://github.com/astral-sh/uv/issues/9513
# https://github.com/pypa/setuptools/issues/4759
license-files = []
