[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "numcodecs_wasm_materialize"
version = "0.1.0"
description = "utility to materialize instances of the `numcodecs-wasm-template` package"

authors = [{ name = "Juniper Tyree", email = "juniper.tyree@helsinki.fi" }]
maintainers = [{ name = "Juniper Tyree", email = "juniper.tyree@helsinki.fi" }]

readme = "README.md"
license = { file = "LICENSE" }

requires-python = ">=3.10"

dependencies = [
    "toml~=0.10.0",
]

[dependency-groups]
dev = [
    "ruff~=0.9.0",
]
