package numcodecs:abc@0.1.0;

interface codec {
    type usize = u32;

    record any-array {
        data: any-array-data,
        shape: list<usize>,
    }

    variant any-array-data {
        %u8(list<u8>),
        %u16(list<u16>),
        %u32(list<u32>),
        %u64(list<u64>),
        i8(list<s8>),
        i16(list<s16>),
        i32(list<s32>),
        i64(list<s64>),
        %f32(list<f32>),
        %f64(list<f64>),
    }

    type error = list<string>;

    resource codec {
        from-config: static func(config: string) -> result<codec, error>;
        encode: func(data: any-array) -> result<any-array, error>;
        decode: func(encoded: any-array) -> result<any-array, error>;
        get-config: func() -> result<string, error>;
    }

    codec-id: func() -> string;
}
