package numcodecs:abc@0.1.1;

world imports {
    import codec;
}

world exports {
    export codec;
}

@since(version = 0.1.1)
world imports-with-registry {
    import codec;
    export registry;
}

@since(version = 0.1.1)
world exports-with-registry {
    export codec;
    import registry;
}
